# Generated by Django 3.1.2 on 2020-11-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20201128_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='sku',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
