# Generated by Django 3.1.2 on 2020-11-30 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20201130_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='user_id',
        ),
    ]
