# Generated by Django 3.1.2 on 2020-10-26 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_extra'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='design_packs',
            options={'verbose_name_plural': 'Design_Packs'},
        ),
        migrations.AlterModelOptions(
            name='extra',
            options={'verbose_name_plural': 'Extras'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Products'},
        ),
    ]
